name: Monitor eBay Pokémon

on:
  schedule:
    - cron: "0 10 * * *"  # roda todo dia às 13h UTC (~10h no horário de Brasília)
  workflow_dispatch:       # permite executar manualmente

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o crawler
        run: python monitor.py

      - name: Gerar JSON com o monitor
        run: python monitor.py

      - name: Commit e push do JSON gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ebay-listing.json
          git commit -m "Update JSON [bot]" || echo "No changes"
          git push

